name: Notificar PR nuevo o actualizado
on:
  pull_request:
    types: [opened, synchronize]
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Send notification
        run: echo "Pull Request ${{ github.event.action }} by ${{ github.event.pull_request.user.login }},  ${{ github.event.pull_request.title }}"
