name: Java CI with Maven

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin' # o 'zulu'
        java-version: '17'

    - name: Build with Maven
      run: mvn -B clean verify
