name: Java CI with Maven

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Build with Maven
      run: ./mvnw -B clean verify
